# osmdatar

R package for downloading OSM data. 


## Speed comparisons

Speed comparisons can be examined in the branch `speed-comparisons`, with the
main branch now just serving the further development of the `Rcpp` versions. The
results from that branch (on test data of highways only) are:

method    |   Computation time (s)
------  | ------    
osmplotr    |   1.86
hrbrmstr    |   1.47    
Rcpp (->`sp` in `R`)    |   0.25
Rcpp (->`sp` in `Rcpp`)    |   0.08

Processing everything, including the construction of the `sp` S4 objects, within
`Rcpp` routines is obviously enourmously faster, and the package will now be
constructed to generalise all other kinds of OSM objects.

------

## Install

```{r, message=FALSE}
Sys.setenv ('PKG_CXXFLAGS'='-std=c++11')
setwd ("..")
#devtools::document ("osmdatar")
devtools::load_all ("osmdatar")
setwd ("./osmdatar")
Sys.unsetenv ('PKG_CXXFLAGS')
```


```{r, eval=FALSE}
txt <- get_xml_doc3 (bbox=bbox)
mb3e <- microbenchmark ( obj3 <- process_xml_doc3e (txt), times=100L )
mb3f <- microbenchmark ( obj3 <- process_xml_doc3f (txt), times=100L )
tt3e <- formatC (mean (mb3e$time) / 1e9, format="f", digits=2)
tt3f <- formatC (mean (mb3f$time) / 1e9, format="f", digits=2)
```
```{r, echo=FALSE}
tt3e <- 0.11
tt3f <- 0.08
```
```{r}
cat ("Mean time to convert with Rcpp+sp code = (", tt3e, ", ", tt3f, 
     ")\n", sep="")
```
