// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_highways
List get_highways(std::string st);
RcppExport SEXP osmdatar_get_highways(SEXP stSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type st(stSEXP);
    __result = Rcpp::wrap(get_highways(st));
    return __result;
END_RCPP
}
