// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_get_ways
Rcpp::S4 rcpp_get_ways(std::string st);
RcppExport SEXP osmdatar_rcpp_get_ways(SEXP stSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type st(stSEXP);
    __result = Rcpp::wrap(rcpp_get_ways(st));
    return __result;
END_RCPP
}
