/***************************************************************************
 *  Project:    osmdata
 *  File:       sf-tests.cpp
 *  Language:   C++
 *
 *  osmdata is free software: you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free
 *  Software Foundation, either version 3 of the License, or (at your option)
 *  any later version.
 *
 *  osmdata is distributed in the hope that it will be useful, but WITHOUT ANY
 *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 *  details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  osm-router.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Author:     Mark Padgham / Andrew Smith
 *  E-Mail:     mark.padgham@email.com / andrew@casacazaz.net
 *
 *  Description:    Functions only used in tests/testthat/test-sf-rcpp.R to
 *                  compare construction of 'sf' objects in 'osmdata' with
 *                  equivalent objects constructed using 'sf'.  These functions
 *                  are necessary because the results of 'sf::st_read()' can not
 *                  be directly compared with the output of 'omsdata', because
 *                  GDAL does not return all key-value pairs, whereas 'osmdata'
 *                  does, and the two will never be identical.
 *
 *  Limitations:
 *
 *  Dependencies:       none 
 *
 *  Compiler Options:   -std=c++11
 ***************************************************************************/


#include <Rcpp.h>

//' rcpp_test_points
//'
//' Reproduces code used in src/osmdata.cpp to compare Rcpp construction of
//' sfg::POINT' objects in ' osmdata with equivalent construction in sf
//' generated by
//' 'sf::st_sfc (a=sf::st_point (c(1.0,2.0)), b=sf::st_point (c(3.0,4.0)))
//'
//' @return An sf Simple Features Collection object of 'sfg::POINT' objects
// [[Rcpp::export]]
Rcpp::List rcpp_test_points () {
    Rcpp::List crs = Rcpp::List::create (NA_INTEGER, 
            Rcpp::CharacterVector::create (NA_STRING));
    crs.attr ("class") = "crs";
    crs.attr ("names") = Rcpp::CharacterVector::create ("epsg", "proj4string");

    std::vector <std::string> names;
    names.push_back ("xmin");
    names.push_back ("ymin");
    names.push_back ("xmax");
    names.push_back ("ymax");
    Rcpp::NumericVector bbox (4, NA_REAL);
    bbox (0) = 1;
    bbox (1) = 2;
    bbox (2) = 3;
    bbox (3) = 4;
    bbox.attr ("names") = names;

    Rcpp::List pointList (2);

    // Just for this test
    Rcpp::CharacterVector ptnms = Rcpp::CharacterVector::create ("a", "b");
    // Actual code from rcpp_osmdata_sf:
    //std::vector <std::string> ptnames;
    //ptnames.reserve (2);

    for (int i=0; i<2; i++)
    {
        Rcpp::NumericVector ptxy = Rcpp::NumericVector::create (NA_REAL, NA_REAL);
        ptxy.attr ("class") = Rcpp::CharacterVector::create ("XY", "POINT", "sfg");
        ptxy [0] = 2 * i + 1;
        ptxy [1] = 2 * i + 2;
        pointList (i) = ptxy;
    }

    pointList.attr ("names") = ptnms;
    pointList.attr ("n_empty") = 0;
    pointList.attr ("class") = Rcpp::CharacterVector::create ("sfc_POINT", "sfc");
    pointList.attr ("precision") = 0.0;
    pointList.attr ("bbox") = bbox;
    pointList.attr ("crs") = crs;
    return pointList;
}

//' rcpp_test_lines
//'
//' Reproduces code used in src/osmdata.cpp to compare Rcpp construction of
//' sfg::POINT' objects in ' osmdata with equivalent construction in sf
//' generated with this code:
//' l1 <- sf::st_linestring (cbind (c(1.0,2.0,3.0,4.0), c(5.0,6.0,7.0,8.0)))
//' l2 <- sf::st_linestring (cbind (c(11.0,12.0,13.0), c(14.0,15.0,16.0)))
//' y <- sf::st_sfc (a=l1, b=l2)
//'
//' @return An sf Simple Features Collection object of 'sfg::POINT' objects
// [[Rcpp::export]]
Rcpp::List rcpp_test_lines () {
    Rcpp::List crs = Rcpp::List::create (NA_INTEGER, 
            Rcpp::CharacterVector::create (NA_STRING));
    crs.attr ("class") = "crs";
    crs.attr ("names") = Rcpp::CharacterVector::create ("epsg", "proj4string");

    std::vector <std::string> names;
    names.push_back ("xmin");
    names.push_back ("ymin");
    names.push_back ("xmax");
    names.push_back ("ymax");
    Rcpp::NumericVector bbox (4, NA_REAL);
    bbox (0) = 1;
    bbox (1) = 5;
    bbox (2) = 13;
    bbox (3) = 16;
    bbox.attr ("names") = names;

    Rcpp::List lineList (2);

    // Just for this test
    Rcpp::CharacterVector ptnms = Rcpp::CharacterVector::create ("a", "b");
    // Actual code from rcpp_osmdata_sf:
    //std::vector <std::string> ptnames;
    //ptnames.reserve (2);

    Rcpp::NumericMatrix lnxy1 (Rcpp::Dimension (4, 2));
    std::fill (lnxy1.begin (), lnxy1.end (), NA_REAL);
    lnxy1 (0, 0) = 1;
    lnxy1 (1, 0) = 2;
    lnxy1 (2, 0) = 3;
    lnxy1 (3, 0) = 4;
    lnxy1 (0, 1) = 5;
    lnxy1 (1, 1) = 6;
    lnxy1 (2, 1) = 7;
    lnxy1 (3, 1) = 8;
    lnxy1.attr ("class") = Rcpp::CharacterVector::create ("XY", "LINESTRING", "sfg");
    lineList (0) = lnxy1;

    Rcpp::NumericMatrix lnxy2 (Rcpp::Dimension (3, 2));
    std::fill (lnxy2.begin (), lnxy2.end (), NA_REAL);
    lnxy2 (0, 0) = 11;
    lnxy2 (1, 0) = 12;
    lnxy2 (2, 0) = 13;
    lnxy2 (0, 1) = 14;
    lnxy2 (1, 1) = 15;
    lnxy2 (2, 1) = 16;
    lnxy2.attr ("class") = Rcpp::CharacterVector::create ("XY", "LINESTRING", "sfg");
    lineList (1) = lnxy2;

    lineList.attr ("names") = ptnms;
    lineList.attr ("n_empty") = 0;
    lineList.attr ("class") = Rcpp::CharacterVector::create ("sfc_LINESTRING", "sfc");
    lineList.attr ("precision") = 0.0;
    lineList.attr ("bbox") = bbox;
    lineList.attr ("crs") = crs;
    return lineList;
}
