# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_osmdata
#'
#' Extracts all polygons from an overpass API query
#'
#' @param st Text contents of an overpass API query
#' @return Rcpp::List objects of OSM data
rcpp_osmdata <- function(st) {
    .Call('osmdata_rcpp_osmdata', PACKAGE = 'osmdata', st)
}

#' rcpp_osmdata_sp
#'
#' Extracts all polygons from an overpass API query
#'
#' @param st Text contents of an overpass API query
#' @return A \code{SpatialLinesDataFrame} contains all polygons and associated data
rcpp_osmdata_sp <- function(st) {
    .Call('osmdata_rcpp_osmdata_sp', PACKAGE = 'osmdata', st)
}

#' rcpp_test_points
#'
#' Reproduces code used in src/osmdata.cpp to compare Rcpp construction in
#' osmdata with equivalent construction in sf. The results of 'sf::st_read()'
#' can not be directly compared with the results of 'omsdata', because GDAL does
#' not return all key-value pairs, whereas 'osmdata' does, and the two will never
#' be identical. The 'Rcpp' construction of 'sf' objects can thus only be checked
#' in highly simplified examples like this. This function is only used in
#' 'tests/testthat/test-sf-rcpp.R'.
#'
#' @return An sf Simple Features Collection object
rcpp_test_points <- function() {
    .Call('osmdata_rcpp_test_points', PACKAGE = 'osmdata')
}

