# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_get_nodes
#'
#' Extracts all nodes from an overpass API query
#'
#' @param st Text contents of an overpass API query
#' @return A SpatialPointsDataFrame contains all nodes and associated data
#' @export
rcpp_get_nodes <- function(st) {
    .Call('osmdatar_rcpp_get_nodes', PACKAGE = 'osmdatar', st)
}

#' rcpp_get_ways
#'
#' Extracts all nodes from an overpass API query
#'
#' @param st Text contents of an overpass API query
#' @return A SpatialLinesDataFrame contains all ways and associated data
#' @export
rcpp_get_ways <- function(st) {
    .Call('osmdatar_rcpp_get_ways', PACKAGE = 'osmdatar', st)
}

