# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_get_nodes <- function(st) {
    .Call('osmdatar_rcpp_get_nodes', PACKAGE = 'osmdatar', st)
}

rcpp_get_ways <- function(st) {
    .Call('osmdatar_rcpp_get_ways', PACKAGE = 'osmdatar', st)
}

